### PR TITLE
XS✔ ◾ Add link check and spell check and style check

### PR DESCRIPTION
**Pull request by karl-johan-grahn**
Add checks for docs and PR metrics

### CODE REVIEW

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-8bff61e7`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-43c85a54`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-86282f7c`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-9061a35d`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2cf6e4ad`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-c8d968d7`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-a9d62364`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-400acf0e`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-1673bb92`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-83b5d15a`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-05954ef3`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-89da4fb1`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-e20fb1e6`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2049c95f`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-91a35115`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-c93298ed`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-54e36883`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-c387dd70`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-d7eddf34`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-0ee6c6a3`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-74e1af42`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-a297bc2d`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-46017688`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-93b0d07f`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-58eae81f`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-caec4f00`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-83105098`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-9fa064d6`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-dd45affe`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2cb18841`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2cb18841`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-150c98ef`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-150c98ef`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-25bf7d5e`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-25bf7d5e`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2dba065c`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-2dba065c`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-9419cb99`

**Comment by stakater-user** [comment]
@callum-stakater Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-9419cb99`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-186ad9b2`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-186ad9b2`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-dc035963`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-d8e1326d`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull stakater/workshop-excercise:SNAPSHOT-PR-54-d8e1326d`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
